name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: action/checkout@v4
      - name: "Install Dependency"
        run: echo "Install...."
