name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    brunches:
      - develop
      - 'release-*' # release-1.2.3 relese-esteira release-prod
      - 'feat/**' # feature/actions
    paths-ignore:
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Install Dependency"
        run: echo "Install...."
